# -*- mode: ruby -*-
# vi: set ft=ruby :

# See README.md for details

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  config.vm.box = "centos/7"

  config.vm.provider "virtualbox" do |v|
    v.memory = 2000
    v.cpus = 1
    v.name = "Vagrant-PuppetMaster"
    v.gui = false
  end

  config.vm.define "puppetmaster" do |puppetmaster|

    puppetmaster.vm.hostname = "puppetmaster"

    puppetmaster.vm.network "private_network", ip: "172.31.0.201"

  end

end