# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.ssh.insert_key = true
  config.ssh.username = "vagrant"
  
  config.vm.define "puppet_master_box" do |pm|
    pm.vm.box = "centos/7"
    pm.vm.hostname = "puppetmaster"
	  pm.vm.network "private_network", ip: "192.168.33.10"
    
  	pm.vm.provider "virtualbox" do |v|
      v.memory = 4000
      v.cpus = 1
      v.name = "Vagrant-PuppetMaster"
      v.gui = false
	  end

    pm.vm.provision "shell", inline: "/vagrant/scripts/install-puppetmaster.sh" 
  end

  config.vm.define "puppet_agent_box" do |pa|
    pa.vm.box = "centos/7"
    pa.vm.hostname = "puppetagent"
	  pa.vm.network "private_network", ip: "192.168.33.11"
    
  	pa.vm.provider "virtualbox" do |v|
      v.memory = 4000
      v.cpus = 1
      v.name = "Vagrant-PuppetAgent"
      v.gui = false
	  end

    pa.vm.provision "shell", inline: "/vagrant/scripts/install-puppetagent.sh" 
  end

end