forge "https://forgeapi.puppetlabs.com"

mod "puppetlabs-stdlib"
mod "puppetlabs-ntp"
mod 'puppetlabs-limits'
mod 'puppetlabs-concat'
mod 'puppetlabs-inifile'
mod 'puppetlabs-translate', '2.2.0'

mod "herculesteam-augeasproviders_core"
mod "herculesteam-augeasproviders_ssh"
mod "herculesteam-augeasproviders_grub"

mod 'ericsson-motd', '1.0.3'

mod 'camptocamp-kmod', '2.1.0'

mod 'joshbeard-login_defs', '0.2.0'

mod 'kemra102-auditd', '2.2.0'

mod 'thias-sysctl', '1.0.6'

mod 'saz-sudo', '6.0.0'

mod 'puppet-gitlab', '5.1.0'
mod 'puppetlabs-java', '6.3.0'
mod 'puppet-python', '4.1.1'
mod 'stahnma-epel', '1.3.1'
